# Generated by Django 4.2.6 on 2023-11-01 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog_app', '0004_alter_comment_author_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=100)),
                ('image_caption', models.TextField(max_length=350)),
                ('image_likes', models.IntegerField(default=0)),
                ('image_comments', models.IntegerField(default=0)),
                ('image_created_at', models.DateTimeField(auto_now_add=True)),
                ('image_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
