# Generated by Django 4.2.6 on 2023-11-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0008_remove_profile_user_id_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
    ]
