# Generated by Django 4.2.6 on 2023-11-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0009_rename_author_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='author',
        ),
    ]
