# Generated by Django 4.2.6 on 2023-11-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0011_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
