# Generated by Django 4.2.6 on 2023-11-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0013_post_image_post_likes_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
