# Generated by Django 4.2.6 on 2023-11-09 20:26

import Blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0014_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog_app.models.upload_to),
        ),
    ]
