# Generated by Django 4.2.6 on 2023-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0017_rename_author_id_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(null=True),
        ),
    ]
